kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - master

steps:
  - name: Build
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      port:
        from_secret: port
      key:
        from_secret: ssh_key
      script:
        - cd /apps/backup/please/fail/dir/not/exists
        - git checkout maste
        - git pul
        - docke build -t backup:latest .

  - name: Deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      port:
        from_secret: port
      key:
        from_secret: ssh_key
      script:
        - /apps/updateBackups.sh

  - name: notify
    image: drillster/drone-email
    host:
      from_secret: mail_host
    port:
      from_secret: mail_port
    username:
      from_secret: mail_user
    password:
      from_secret: mail_pass
    from:
      from_secret: mail_user
    when:
      status: [ changed, failure ]
