kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - master

steps:
  - name: build
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      port:
        from_secret: port
      key:
        from_secret: ssh_key
      script:
        - cd /apps/backup/
        - git checkout master
        - git pull
        - docker build -t apoutchika/backup:latest .

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      port:
        from_secret: port
      key:
        from_secret: ssh_key
      script:
        - /apps/updateBackups.sh

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: mail_host
      username:
        from_secret: mail_user
      password:
        from_secret: mail_pass
      port:
        from_secret: mail_port
      from:
        from_secret: mail_from
      when:
        status: [ changed, failure ]
    when:
      status:
        - changed
        - failure
